# **Setup**

* https://towardsdatascience.com/animating-spatial-movement-in-python-ccf4e9462a0f

In [24]:
import geopandas as gpd
import pandas as pd
from IPython.display import clear_output

# **Data Import**

In [25]:
# Import data from csv
data = pd.read_csv("https://data.urbansharing.com/oslobysykkel.no/trips/v1/2023/10.csv")
data = data[['started_at','ended_at','duration', 'start_station_latitude', 'start_station_longitude','end_station_latitude', 'end_station_longitude']]

# Subset the data to only one day
data['start_day'] = data['started_at'].apply(lambda x: int(x[8:11]))
data

,started_at,ended_at,duration,start_station_latitude,start_station_longitude,end_station_latitude,end_station_longitude,start_day
0,2023-10-01 00:00:40.773000+00:00,2023-10-01 00:04:34.682000+00:00,233,59.919147,10.764130,59.915649,10.761725,1
1,2023-10-01 03:01:18.390000+00:00,2023-10-01 03:08:24.193000+00:00,425,59.932772,10.758595,59.939244,10.774319,1
2,2023-10-01 03:06:04.201000+00:00,2023-10-01 03:09:44.839000+00:00,220,59.917279,10.758155,59.920128,10.768875,1
3,2023-10-01 03:23:28.695000+00:00,2023-10-01 03:30:50.497000+00:00,441,59.910331,10.750110,59.905323,10.768958,1
4,2023-10-01 03:27:53.417000+00:00,2023-10-01 03:38:53.295000+00:00,659,59.920995,10.750358,59.917085,10.712880,1
...,...,...,...,...,...,...,...,...
112550,2023-10-31 23:14:18.394000+00:00,2023-10-31 23:19:29.346000+00:00,310,59.910871,10.729829,59.917968,10.738629,31
112551,2023-10-31 23:18:59.424000+00:00,2023-10-31 23:23:50.695000+00:00,291,59.912183,10.754434,59.913202,10.767579,31
112552,2023-10-31 23:32:46.288000+00:00,2023-10-31 23:39:50.518000+00:00,424,59.913897,10.742310,59.915451,10.758328,31
112553,2023-10-31 23:44:08.525000+00:00,2023-10-31 23:49:42.641000+00:00,334,59.912793,10.710103,59.918014,10.718435,31
112554,2023-10-31 23:58:49.511000+00:00,2023-11-01 00:01:49.741000+00:00,180,59.940252,10.716724,59.935220,10.726477,31

In [26]:
data['start_day'].value_counts().sort_values(ascending=True)

start_day
30    1212
31    1580
29    1684
22    1777
21    1826
8     2411
28    2483
15    2770
1     2891
7     3014
6     3156
13    3263
14    3266
27    3732
20    3781
10    3910
23    4037
25    4200
26    4220
24    4265
19    4295
16    4468
9     4543
17    4587
2     4776
5     4861
18    4895
11    5098
4     5127
12    5211
3     5216
Name: count, dtype: int64

In [28]:
# Select The Day For Visualization
day = 30

In [29]:
data = data[data["start_day"]==day]
data

,started_at,ended_at,duration,start_station_latitude,start_station_longitude,end_station_latitude,end_station_longitude,start_day
109763,2023-10-30 04:06:04.994000+00:00,2023-10-30 04:14:50.275000+00:00,525,59.937800,10.754100,59.929045,10.716926,30
109764,2023-10-30 04:19:00.302000+00:00,2023-10-30 04:31:52.125000+00:00,771,59.920995,10.750358,59.917085,10.712880,30
109765,2023-10-30 04:19:27.830000+00:00,2023-10-30 04:21:14.499000+00:00,106,59.924403,10.713069,59.924403,10.713069,30
109766,2023-10-30 04:22:34.345000+00:00,2023-10-30 04:28:29.797000+00:00,355,59.914306,10.720202,59.914586,10.735453,30
109767,2023-10-30 04:26:41.357000+00:00,2023-10-30 04:30:57.619000+00:00,256,59.918636,10.752394,59.912522,10.750910,30
...,...,...,...,...,...,...,...,...
110970,2023-10-30 23:10:18.403000+00:00,2023-10-30 23:24:05.872000+00:00,827,59.925265,10.750462,59.939230,10.759170,30
110971,2023-10-30 23:18:52.782000+00:00,2023-10-30 23:36:26.920000+00:00,1054,59.906920,10.760312,59.904473,10.786167,30
110972,2023-10-30 23:54:32.216000+00:00,2023-10-31 00:10:50.278000+00:00,978,59.922485,10.720896,59.920404,10.691147,30
110973,2023-10-30 23:56:22.992000+00:00,2023-10-31 00:09:05.767000+00:00,762,59.913360,10.737663,59.925471,10.731219,30
110974,2023-10-30 23:57:51.609000+00:00,2023-10-31 00:19:14.402000+00:00,1282,59.914871,10.701037,59.925488,10.746058,30

In [30]:
data.reset_index(drop=True,inplace=True)
data

,started_at,ended_at,duration,start_station_latitude,start_station_longitude,end_station_latitude,end_station_longitude,start_day
0,2023-10-30 04:06:04.994000+00:00,2023-10-30 04:14:50.275000+00:00,525,59.937800,10.754100,59.929045,10.716926,30
1,2023-10-30 04:19:00.302000+00:00,2023-10-30 04:31:52.125000+00:00,771,59.920995,10.750358,59.917085,10.712880,30
2,2023-10-30 04:19:27.830000+00:00,2023-10-30 04:21:14.499000+00:00,106,59.924403,10.713069,59.924403,10.713069,30
3,2023-10-30 04:22:34.345000+00:00,2023-10-30 04:28:29.797000+00:00,355,59.914306,10.720202,59.914586,10.735453,30
4,2023-10-30 04:26:41.357000+00:00,2023-10-30 04:30:57.619000+00:00,256,59.918636,10.752394,59.912522,10.750910,30
...,...,...,...,...,...,...,...,...
1207,2023-10-30 23:10:18.403000+00:00,2023-10-30 23:24:05.872000+00:00,827,59.925265,10.750462,59.939230,10.759170,30
1208,2023-10-30 23:18:52.782000+00:00,2023-10-30 23:36:26.920000+00:00,1054,59.906920,10.760312,59.904473,10.786167,30
1209,2023-10-30 23:54:32.216000+00:00,2023-10-31 00:10:50.278000+00:00,978,59.922485,10.720896,59.920404,10.691147,30
1210,2023-10-30 23:56:22.992000+00:00,2023-10-31 00:09:05.767000+00:00,762,59.913360,10.737663,59.925471,10.731219,30
1211,2023-10-30 23:57:51.609000+00:00,2023-10-31 00:19:14.402000+00:00,1282,59.914871,10.701037,59.925488,10.746058,30

# **Creating Movement Lines**

In [31]:
import osmnx as ox
from shapely.geometry import Polygon

# Create a GeoDataFrame from the stations
initial_data = gpd.GeoDataFrame(data, geometry=gpd.points_from_xy(data['start_station_longitude'],data['start_station_latitude']),crs="EPSG:4326")
# Get the total bounds
total_bounds = initial_data.total_bounds

# Create a list for the polygon
bounding_box = [[total_bounds[0],total_bounds[3]], [total_bounds[0],total_bounds[1]], [total_bounds[2],total_bounds[1]], [total_bounds[2],total_bounds[3]]]

# Create the polygon
bounding_box_polygon = Polygon(bounding_box)

# Buffer the polygon to include roads just outside of the stations
graph_extent = bounding_box_polygon.buffer(0.02)

# Create the graph
area_graph = ox.graph_from_polygon(graph_extent, network_type='bike')
nodes, edges = ox.graph_to_gdfs(area_graph)

# **Calculate Shortest Path**

In [32]:
import networkx as nx
from shapely import ops

def calculate_shortest_path(start_point,end_point, graph):
    # Find the nearest node to the start and end points
    start_node = ox.distance.nearest_nodes(graph, X=start_point.x, Y=start_point.y)
    end_node = ox.distance.nearest_nodes(graph, X=end_point.x, Y=end_point.y)
    
    # Calculate the shortest path
    path = nx.dijkstra_path(graph, source=start_node, target=end_node, weight='length')
    
    # Convert the network path to a LineString
    geoms = [edges.loc[(u, v, 0), 'geometry'] for u, v in zip(path[:-1], path[1:])]
    route_lineString = MultiLineString(geoms)
    route_lineString = ops.linemerge(route_lineString)
    return route_lineString

In [33]:
from shapely.geometry import Point
from shapely.geometry import MultiLineString
data['start_point'] = data.apply(lambda row: Point(row['start_station_longitude'],row['start_station_latitude']), axis=1)
data['end_point'] = data.apply(lambda row: Point(row['end_station_longitude'],row['end_station_latitude']), axis=1)

C:\Users\aksha\AppData\Local\Temp\ipykernel_7348\3582632268.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['start_point'] = data.apply(lambda row: Point(row['start_station_longitude'],row['start_station_latitude']), axis=1)
C:\Users\aksha\AppData\Local\Temp\ipykernel_7348\3582632268.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['end_point'] = data.apply(lambda row: Point(row['end_station_longitude'],row['end_station_latitude']), axis=1)

In [ ]:
# data['shortest_path'] = data.apply(lambda row: calculate_shortest_path(row['start_point'],row['end_point'],area_graph), axis=1)
# print(data.head())

In [36]:
data.shape

(1212, 11)

In [35]:
for i in data.index:
    print(f'Processing Row No: {i}')
    data.loc[i,'shortest_path'] = calculate_shortest_path(data.loc[i,'start_point'],data.loc[i,'end_point'],area_graph)
    print(data.loc[i,'shortest_path'])
    clear_output(wait=True)

Processing Row No: 1211
LINESTRING (10.7011154 59.9149731, 10.7011588 59.9149384, 10.7012906 59.9148502, 10.7014715 59.9147447, 10.7015421 59.9147112, 10.7017469 59.914614, 10.7017977 59.9145721, 10.7019418 59.9144533, 10.7019971 59.9144242, 10.7025483 59.9141749, 10.7026388 59.914147, 10.7027559 59.9141181, 10.7028462 59.9140674, 10.7030354 59.9139797, 10.7033586 59.913815, 10.7034833 59.9137609, 10.7035995 59.9137168, 10.7037884 59.9136599, 10.7041532 59.9135557, 10.7052709 59.9132594, 10.706 59.9130601, 10.7061017 59.9130343, 10.7062155 59.913011, 10.7063377 59.9129882, 10.706479 59.9129678, 10.7066359 59.9129549, 10.7070727 59.9129404, 10.707117 59.9129391, 10.7072394 59.9129355, 10.7074138 59.9129302, 10.7076218 59.9129228, 10.7087808 59.9128859, 10.7089513 59.9128805, 10.7091966 59.9128733, 10.7104363 59.9128367, 10.7105786 59.9128325, 10.7106025 59.9128152, 10.7106301 59.9127953, 10.710717 59.9127642, 10.711514 59.9127411, 10.7116251 59.9127446, 10.7117596 59.9127674, 10.7118571 59.9128068, 10.7120535 59.912865, 10.7122887 59.9129398, 10.7129648 59.9131928, 10.7134708 59.9133821, 10.713964 59.9135667, 10.7141487 59.9136352, 10.7149506 59.9139327, 10.7150376 59.913963, 10.7151306 59.9139953, 10.715272 59.9140388, 10.7154285 59.9140829, 10.7155871 59.9141194, 10.7159525 59.9141952, 10.7160375 59.914213, 10.7173113 59.9144793, 10.7174086 59.9145044, 10.7174943 59.9145269, 10.717604 59.9145641, 10.7176685 59.914551, 10.7177375 59.9145466, 10.7178065 59.9145509, 10.7178711 59.9145639, 10.7179272 59.9145845, 10.7179511 59.9145976, 10.7181372 59.9146127, 10.7183026 59.9146357, 10.7184194 59.9146596, 10.7197778 59.9149319, 10.7201001 59.9150053, 10.7202477 59.9150409, 10.720415 59.9150717, 10.7206014 59.9150982, 10.7209654 59.9151247, 10.7223269 59.9152013, 10.7224204 59.9152036, 10.7225181 59.9152012, 10.7225487 59.9151929, 10.7225818 59.9151877, 10.7226206 59.9151856, 10.7226595 59.9151877, 10.7226965 59.9151938, 10.7227303 59.9152036, 10.7227591 59.9152168, 10.7227829 59.9152337, 10.7227987 59.9152529, 10.7228058 59.915272, 10.7228049 59.9152875, 10.7228003 59.9153007, 10.7227877 59.9153179, 10.7227643 59.9153356, 10.7227279 59.9153524, 10.7227008 59.9153605, 10.7226702 59.9153679, 10.7226585 59.9153971, 10.7226514 59.915426, 10.7226493 59.9154653, 10.7226453 59.9155367, 10.7226117 59.9156006, 10.7228448 59.91662, 10.7228589 59.9166818, 10.7228761 59.9167501, 10.7229168 59.9169118, 10.7229466 59.9169742, 10.7229955 59.9170253, 10.7230606 59.9170747, 10.7243847 59.9179667, 10.7244527 59.9180125, 10.7245306 59.9180636, 10.7248974 59.9183045, 10.7252222 59.9185179, 10.7253877 59.9186267, 10.7256713 59.918813, 10.725832 59.9189186, 10.7259564 59.9190025, 10.7262602 59.9192075, 10.7271001 59.9197738, 10.7271779 59.9198263, 10.7276081 59.9200995, 10.7276944 59.9201276, 10.7277126 59.9201336, 10.7277807 59.920153, 10.7278409 59.9201661, 10.7279228 59.9201806, 10.7279446 59.920177, 10.7279673 59.9201753, 10.7279903 59.9201754, 10.7280319 59.9201809, 10.728068 59.9201925, 10.7280952 59.9202092, 10.7281107 59.9202293, 10.728113 59.9202509, 10.7281077 59.9202639, 10.7280974 59.9202763, 10.7280825 59.9202874, 10.7280935 59.9203056, 10.7281096 59.9203213, 10.7281721 59.9203642, 10.7284814 59.9205748, 10.7285101 59.9206513, 10.7285307 59.9206739, 10.7285356 59.9206995, 10.72854 59.9207222, 10.7285372 59.9207413, 10.7285349 59.920757, 10.7285855 59.9207607, 10.7286523 59.9207756, 10.7286936 59.9207941, 10.7289263 59.9209032, 10.7292588 59.9210828, 10.7294833 59.921204, 10.7295447 59.9212372, 10.7296409 59.9212856, 10.7298131 59.9213733, 10.7298534 59.9213927, 10.7300204 59.9214734, 10.7302136 59.9215667, 10.7314765 59.9221943, 10.7315069 59.9222091, 10.7317997 59.922352, 10.7320333 59.9224605, 10.7320301 59.9225069, 10.7320195 59.9225962, 10.7320029 59.9227174, 10.7319903 59.922791, 10.7319726 59.9228645, 10.7319564 59.922907, 10.7319366 59.9229498, 10.7319608 59.922951, 10.7320664 59.9229564, 10.7321023 59.9229582, 10.732626 59.9229848, 10.7334369 59.9230214, 10.7337954 59.9230361, 10.7345911 59.9230688, 10.7351882 59.9230941, 10.7353262 59.9231002, 10.7354415 59.9231046, 10.7361618 59.9231338, 10.7362694 59.9231379, 10.7363592 59.923148, 10.7364157 59.9231646, 10.7365537 59.9231168, 10.7372465 59.9228767, 10.7373948 59.9228257, 10.7377865 59.922691, 10.737855 59.9226706, 10.7379263 59.9226588, 10.7380034 59.9226567, 10.7380873 59.9226681, 10.7381644 59.922684, 10.7382491 59.9227147, 10.7386954 59.9229335, 10.7389661 59.9230639, 10.7396326 59.9233849, 10.7398777 59.9235031, 10.7399924 59.9235609, 10.7401056 59.9236156, 10.7402183 59.9236665, 10.7406555 59.9238713, 10.7411177 59.9240879, 10.7411985 59.9241226, 10.7412883 59.9241579, 10.7413623 59.9241891, 10.7414232 59.9242143, 10.741725 59.9243595, 10.7424912 59.9247258, 10.7429006 59.9249227, 10.7430958 59.9249815, 10.7431491 59.9250056, 10.7432541 59.9250581, 10.7435044 59.9251791, 10.7435408 59.9251968, 10.7436526 59.9252842, 10.7440164 59.9254539, 10.7441639 59.925493, 10.7442075 59.9255138, 10.7443296 59.9255717, 10.7444064 59.9255309, 10.7452088 59.9251086, 10.7452989 59.9250613, 10.7453981 59.9251099, 10.7460009 59.9254052)

In [37]:
# Update Time Format For Display
from datetime import datetime
data['started_at'] = data['started_at'].apply(lambda x: datetime.strptime(x[0:19], "%Y-%m-%d %H:%M:%S"))
data['ended_at'] = data['ended_at'].apply(lambda x: datetime.strptime(x[0:19], "%Y-%m-%d %H:%M:%S"))

C:\Users\aksha\AppData\Local\Temp\ipykernel_7348\3385928409.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['started_at'] = data['started_at'].apply(lambda x: datetime.strptime(x[0:19], "%Y-%m-%d %H:%M:%S"))
C:\Users\aksha\AppData\Local\Temp\ipykernel_7348\3385928409.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ended_at'] = data['ended_at'].apply(lambda x: datetime.strptime(x[0:19], "%Y-%m-%d %H:%M:%S"))

# **Splitting Up Lines**

In [50]:
def line_to_points(df):
  # Create a dataframe for our points
  point_df = pd.DataFrame(columns=['x','y','time','dateminute','size'])
  # Iterate over the line data
  for idx, line in df.iterrows():
    start_x = line['shortest_path'].coords.xy[0][0]
    start_y = line['shortest_path'].coords.xy[1][0]
    # Create number of sections based on duration of trip
    delta = line['ended_at']-line['started_at']
    sections = line['duration']/15
    time_gap = delta/sections
    # Create initial point
    point_time = line['started_at']
    size = 10
    # Create timestamp
    dateminute = int(str(line['started_at'].year)+str(line['started_at'].month).zfill(2)+str(line['started_at'].day).zfill(2)+str(line['started_at'].hour).zfill(2)+str(line['started_at'].minute).zfill(2))
    append_list = [start_x,start_y,point_time.strftime("%Y-%m-%d %H:%M:%S"),dateminute,size]
    point_series = pd.Series(append_list,index=point_df.columns)

    # Add Rows To Dataframe
    point_df = point_df.append(point_series, ignore_index=True)
    # point_df = pd.concat([point_df,point_series], ignore_index=True)
    # Iterate over rest of the sections, size relative to time
    i = 1
    while i <=sections:
      size = 50
      point_time += time_gap
      this_section = i/sections
      new_point = line['shortest_path'].interpolate(this_section, normalized=True)
      dateminute = int(str(point_time.year)+str(point_time.month).zfill(2)+str(point_time.day).zfill(2)+str(point_time.hour).zfill(2)+str(point_time.minute).zfill(2))
      if i == (sections-1):
        size = 30
      if i == 1:
        size = 30
      if i == (sections):
        size = 10
      point_series = pd.Series([new_point.x,new_point.y,point_time.strftime("%Y-%m-%d %H:%M:%S"),dateminute,size],index=point_df.columns)
      
      # Replace Append With Concat Function
      point_df = point_df.append(point_series, ignore_index=True)
      i+=1
  return point_df

In [51]:
# Create a GeoDataFrame from the paths
paths_gdf = gpd.GeoDataFrame(data, geometry='shortest_path', crs="EPSG:4326")
paths_gdf = paths_gdf[~paths_gdf.is_empty] 
result = line_to_points(paths_gdf)

AttributeError: 'DataFrame' object has no attribute 'append'

# **Animating The Movement**

In [ ]:
# Create geodataframe
gdf = gpd.GeoDataFrame(result, geometry=gpd.points_from_xy(result['x'], result['y']))
gdf['size'] = gdf['size'].astype(float)
gdf.crs = "EPSG:4326"
gdf = gdf.to_crs(epsg=4326)
# Get list of timestamps
times = list(gdf['dateminute'].unique())
times.sort()

In [ ]:
import matplotlib
import matplotlib.pyplot as plt
import contextily as ctx

def plot_minute(minute):
  # Set up the plot parameter
  matplotlib.rcParams.update({'font.size': 16})
  fig, ax = plt.subplots(ncols = 1, figsize=(32,20))
  # Plot all rows before the current minute
  old_minutes = gdf[gdf['dateminute'] < minute]
  old_minutes.to_crs(epsg=4326).plot(ax=ax, color='#1DA1F2',markersize=5, edgecolor=None, linewidth=0, alpha=0.4) # 2 - Projected plot
  # Select and plot the current minute
  minute_gdf = gdf[gdf['dateminute'] == minute]
  minute_gdf.to_crs(epsg=4326).plot(ax=ax, color='#1DA1F2',markersize=minute_gdf['size'], edgecolor=None, linewidth=0.3, alpha=0.8) # 2 - Projected plot
  # Set common boundaries for the plot
  xlim = ([stations_gdf.total_bounds[0],  stations_gdf.total_bounds[2]])
  ylim = ([stations_gdf.total_bounds[1],  stations_gdf.total_bounds[3]])
  ax.set_xlim(xlim)
  ax.set_ylim(ylim)
  # Set time variables
  mi = str(minute)[-2:]
  h = str(minute)[-4:-2]
  #d = str(minute)[-4:-2]
  m = str(minute)[4:6]
  y = str(minute)[:4]
  # Add a basemap
  ctx.add_basemap(ax,crs=minute_gdf.crs.to_string(), source=ctx.providers.CartoDB.DarkMatter)
  ax.set_axis_off()
  # Create text
  ax.text(.5,.9,f'{h}:{mi} - {day}/{m}/{y}',
        horizontalalignment='center',color='white',
        transform=ax.transAxes,size=18)
  plt.tight_layout()
  # Save plot to file
  plt.savefig(f'animation/{minute}.png',transparent=True, dpi=100)
  plt.close()

In [ ]:
for timestamp in times:
  plot_minute(timestamp)

# **Converting To GIF**

In [ ]:
# convert -resize 20% -delay 5 -loop 0 animation/*.png animation.gif